In [2]:
import pandas as pd

In [4]:
prod_cat_name = pd.read_csv('product_category_name_translation.csv')
sel_data7 = pd.read_csv('olist_sellers_dataset.csv')
prod_data6 = pd.read_csv('olist_products_dataset.csv')
order_data2 = pd.read_csv('olist_orders_dataset.csv')
order_rev1 = pd.read_csv('olist_order_reviews_dataset.csv')
order_pay3 = pd.read_csv('olist_order_payments_dataset.csv')
order_it_data5 = pd.read_csv('olist_order_items_dataset.csv')
geo8 = pd.read_csv('olist_geolocation_dataset.csv') # --> Not to merge
cust_data4 = pd.read_csv('olist_customers_dataset.csv')

In [16]:
Merge1 = order_rev1.merge(order_data2, on='order_id', how='left', indicator=False)
Merge2 = Merge1.merge(order_pay3, on='order_id', how='left', indicator=False)
Merge3 = Merge2.merge(cust_data4, on='customer_id', how='left', indicator=False)
Merge4 = Merge3.merge(order_it_data5, on='order_id', how='left', indicator=False)
Merge5 = Merge4.merge(prod_data6, on='product_id', how='left', indicator=False)
Merge6 = Merge5.merge(sel_data7, on='seller_id', how='left', indicator=False)

In [45]:
Merge6.describe()

,review_score,payment_sequential,payment_installments,payment_value,customer_zip_code_prefix,order_item_id,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix
count,119151.000000,119148.000000,119148.000000,119148.000000,119151.000000,118318.000000,118318.000000,118318.000000,116609.000000,116609.000000,116609.000000,118298.000000,118298.000000,118298.000000,118298.000000,118318.000000
mean,3.998514,1.094731,2.941426,172.735670,35033.953253,1.196530,120.649109,20.032587,48.767402,785.950441,2.205113,2112.302803,30.264865,16.619994,23.074896,24442.245322
std,1.412529,0.730117,2.777992,267.770023,29823.224176,0.699467,184.107686,15.836559,10.033526,652.571474,1.717418,3786.673988,16.188992,13.453771,11.749216,27572.843192
min,1.000000,1.000000,0.000000,0.000000,1003.000000,1.000000,0.850000,0.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000,1001.000000
25%,3.000000,1.000000,1.000000,60.850000,11250.000000,1.000000,39.900000,13.080000,42.000000,346.000000,1.000000,300.000000,18.000000,8.000000,15.000000,6429.000000
50%,5.000000,1.000000,2.000000,108.160000,24240.000000,1.000000,74.900000,16.280000,52.000000,600.000000,1.000000,700.000000,25.000000,13.000000,20.000000,13660.000000
75%,5.000000,1.000000,4.000000,189.240000,58475.000000,1.000000,134.900000,21.180000,57.000000,983.000000,3.000000,1800.000000,38.000000,20.000000,30.000000,27972.000000
max,5.000000,29.000000,24.000000,13664.080000,99990.000000,21.000000,6735.000000,409.680000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000,99730.000000

In [21]:
Merge6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119151 entries, 0 to 119150
Data columns (total 39 columns):
review_id                        119151 non-null object
order_id                         119151 non-null object
review_score                     119151 non-null int64
review_comment_title             14189 non-null object
review_comment_message           51250 non-null object
review_creation_date             119151 non-null object
review_answer_timestamp          119151 non-null object
customer_id                      119151 non-null object
order_status                     119151 non-null object
order_purchase_timestamp         119151 non-null object
order_approved_at                118974 non-null object
order_delivered_carrier_date     117065 non-null object
order_delivered_customer_date    115730 non-null object
order_estimated_delivery_date    119151 non-null object
payment_sequential               119148 non-null float64
payment_type                     119148 non-null object
payment_installments             119148 non-null float64
payment_value                    119148 non-null float64
customer_unique_id               119151 non-null object
customer_zip_code_prefix         119151 non-null int64
customer_city                    119151 non-null object
customer_state                   119151 non-null object
order_item_id                    118318 non-null float64
product_id                       118318 non-null object
seller_id                        118318 non-null object
shipping_limit_date              118318 non-null object
price                            118318 non-null float64
freight_value                    118318 non-null float64
product_category_name            116609 non-null object
product_name_lenght              116609 non-null float64
product_description_lenght       116609 non-null float64
product_photos_qty               116609 non-null float64
product_weight_g                 118298 non-null float64
product_length_cm                118298 non-null float64
product_height_cm                118298 non-null float64
product_width_cm                 118298 non-null float64
seller_zip_code_prefix           118318 non-null float64
seller_city                      118318 non-null object
seller_state                     118318 non-null object
dtypes: float64(14), int64(2), object(23)
memory usage: 36.4+ MB

In [38]:
cleaned1 = Merge6.drop(columns=['review_comment_message', 'customer_zip_code_prefix', 'review_comment_title', 'review_id' , 'seller_zip_code_prefix', 'order_id',
                        'review_creation_date', 'review_answer_timestamp'])

In [41]:
cleaned1.columns

Index(['review_score', 'customer_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'customer_unique_id',
       'customer_city', 'customer_state', 'order_item_id', 'product_id',
       'seller_id', 'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_city', 'seller_state'],
      dtype='object')

In [43]:
cleaned1.to_csv('lab_tableau2.csv', index=False)